language: go

go:
    - 1.5.1

cache:
    directories:
        - $HOME/ninjabin

install:
    - ./.travis.install-ninja.sh
    - export PATH=$PATH:~/ninjabin

before_script:
    - source .travis.fix-fork.sh

script:
    - ./.travis.gofmt.sh
    - go test ./...
    - mkdir stage
    - cd stage
    - ../bootstrap.bash
    - ./blueprint.bash
    - diff -us ../build.ninja.in .minibootstrap/build.ninja.in
    - ../tests/test.sh
    - ../tests/test_tree_tests.sh
